name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or specify the version your project needs

      - name: Install dependencies
        run: npm install

      - name: Compile Typescript
        run: tsc --project tsconfig.json

      - name: Copy Resources
        run: cp -R resources build/dist/

      - name: Deploy to Pages
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dist
          CLEAN: true